In [92]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

## Function 1: pdist

In [126]:
# run this code after importing pdist, look at its output
arguments = [[1,2],[9,-4],[5,6],[21,8]]
vector = pdist(arguments, metric='euclidean')
vector

array([10.        ,  5.65685425, 20.88061302, 10.77032961, 16.97056275,
       16.1245155 ])

In [127]:
# now, make your own function
def my_pdist(arguments):
    distances = []
    for arg in arguments:
        tmp_distances = [(((np.asarray(arg) - np.asarray(tmp_arg))**2).sum())**0.5 for tmp_arg in arguments]
        for d in tmp_distances:
            if d not in distances:
                distances.append(d)
    distances.remove(0)
    return np.asarray(distances)

In [128]:
my_pdistances = my_pdist([[1,2],[9,-4],[5,6],[21,8]])
my_pdistances

## Function 2: squareform

In [124]:
# run this code after importing squareform, look at its output
matrix = squareform(vector)
matrix

array([[ 0.        , 10.        ,  5.65685425, 20.88061302],
       [10.        ,  0.        , 10.77032961, 16.97056275],
       [ 5.65685425, 10.77032961,  0.        , 16.1245155 ],
       [20.88061302, 16.97056275, 16.1245155 ,  0.        ]])

In [154]:
# now, make your own function
def my_squareform(vector):
    n = int(np.sqrt(len(vector)*2))+1
    lower = np.tri(n,dtype=bool, k=-1)
    mat_lower = np.zeros((n,n))
    mat_lower[lower] = vector
    return mat_lower + mat_lower.T

In [155]:
my_squareform(my_pdistances)

array([[ 0.        , 10.        ,  5.65685425, 10.77032961],
       [10.        ,  0.        , 20.88061302, 16.97056275],
       [ 5.65685425, 20.88061302,  0.        , 16.1245155 ],
       [10.77032961, 16.97056275, 16.1245155 ,  0.        ]])

### Function 3: linkage

In [1]:
# run each line below after importing linkage, look at its output
linkage(matrix, method='complete', metric='euclidean')
linkage(matrix, method='single', metric='euclidean')
linkage(matrix, method='average', metric='euclidean')

NameError: name 'linkage' is not defined

In [ ]:
# now, make your own function
def my_linkage(arguments):
  pass